### ISSUE TITLE
Add Date, Month and Year

### ISSUE THREAD

**Issue by sumit334** [sumit334/Digital-Clock-#2]

**Comment by sauravraj188** [comment]
i am new to open source , can you please assign this issue to me

**Comment by sauravraj188** [comment]
i am new to open source , can you please assign this issue to me

**Comment by sauravraj188** [comment]
i am new to open source , can you please assign this issue to me .

**Comment by sumit334** [comment]
> i am new to open source , can you please assign this issue to me .

You can go ahead and try it out , but now someone is already assigned

**Comment by Amarjit-Khan** [comment]
Hey, I would like to work on this issue. Can you assign it to me?

**Comment by Kaushals112** [comment]
can you assign me this task

**Comment by sumit334** [comment]
> can you assign me this task

Go ahead I am assigning this task to u

**Comment by Pr3mKum4r** [comment]
i would like to work on this one

**Comment by arushpanwar** [comment]
can you please assign this task to me?

**Comment by sumit334** [comment]
Now As the job have been done by @savi001 , so, I would ask if @Pr3mKum4r would like to change the fonts and design of the date and time formate

**Comment by Pr3mKum4r** [comment]
Kindly Follow the following rules as a maintainer to be a part of Hacktoberfest. As i can see you dont have a CONTRIBUTING.md file.

Add the “hacktoberfest” topic to your repository to OPT-IN TO HACKTOBERFEST and indicate you’re looking for contributions.

Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub or GitLab project.

Add a CONTRIBUTING.md file with contribution guidelines to your repository.

Choose issues that have a well-defined scope and are self-contained.

Adopt a code of conduct to create a greater sense of inclusion and community for contributors.

**Comment by sauravraj188** [comment]
@sumit334 i can change the font an design can u assign this to me??
